name: "App01-Deployment"
on: 
  push:
    branches:
     - main
  pull_request:
    branches:
     - main
  workflow_dispatch:
    inputs:
      Infrastructure:
        description: 'Choose Infrastructure Component'
        required: true
        default: 'AVD Infrastructure'
        type: choice
        options:
          - AVD Infrastructure
          - Appv Infrastructure
      action:
        description: 'Choose action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - Plan
          - Plan&Apply
          - Plan&Destroy

permissions:
      id-token: write
      contents: read

jobs:
  analysis:
    name: Analyse the Terraform
    environment: dev
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_STORAGE_ACCOUNT: 'devopslumen'
      TF_VAR_STORAGE_CONTAINER: 'tfstatefile'
      ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      # - name: Log in with Azure
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      -  name: Echo Secrets (for troubleshooting only)
         run: |
          echo "Client ID: ${{ secrets.AZURE_CLIENT_ID }}"
          echo "Tenant ID: ${{ secrets.AZURE_TENANT_ID }}"
          echo "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      - name: Log in with Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9

      - name: Set Main File Path
        id: set-path
        run: |
          if [[ "${{ github.event.inputs.Infrastructure }}" == "Appv Infrastructure" ]]; then
            echo "Main file from appv folder will be used."
            echo "TFPLAN_PATH=Appv/main.tfplan" >> $GITHUB_ENV
            echo "TFVARS_PATH=Appv/deploy.tfvars" >> $GITHUB_ENV
            echo "BACKEND_CONFIG_PATH="Appv/backend.tf" >> $GITHUB_ENV
          else
            echo "Main file from root folder will be used."
            echo "TFPLAN_PATH=main.tfplan" >> $GITHUB_ENV
            echo "TFVARS_PATH=deploy.tfvars" >> $GITHUB_ENV
            echo "BACKEND_CONFIG_PATH="backend.tf" >> $GITHUB_ENV
          fi
      - name: Terraform Init
        run: terraform init -backend-config="${{ env.BACKEND_CONFIG_PATH }}"

      - name: Terraform plan
        id: plan
        if: ${{ github.event.inputs.action == 'Plan&Apply' || github.event.inputs.action == 'Plan' || github.event.inputs.action == 'Plan&Destroy' }}
        run: terraform plan -out="${{ env.TFPLAN_PATH }}" -var-file="${{ env.TFVARS_PATH }}" 

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: |
          echo "plan failed"
          exit 1

      - name: App01 Infra Deployment
        if: ${{ github.event.inputs.action == 'Plan&Apply' }}
        run: terraform apply --auto-approve "${{ env.TFPLAN_PATH }}"

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'Plan&Destroy' }}
        run: terraform destroy -auto-approve -var-file="${{ env.TFVARS_PATH }}"
     